// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kGW8yEdRUwelgt4BvkFSwt2u7GPCndE',
    appId: '1:691889381035:web:00ebb8d72346644ac221ee',
    messagingSenderId: '691889381035',
    projectId: 'linguotech-c7558',
    authDomain: 'linguotech-c7558.firebaseapp.com',
    storageBucket: 'linguotech-c7558.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLm6VwH98znG-dwEAm9ZZNe9FhrDB6Co',
    appId: '1:691889381035:android:2c19166cfdf29ab2c221ee',
    messagingSenderId: '691889381035',
    projectId: 'linguotech-c7558',
    storageBucket: 'linguotech-c7558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCckzqiFnSo7LjSdOc0Kx9BHQ23A73s4',
    appId: '1:691889381035:ios:6dcccc4ec97b86eec221ee',
    messagingSenderId: '691889381035',
    projectId: 'linguotech-c7558',
    storageBucket: 'linguotech-c7558.appspot.com',
    iosBundleId: 'com.example.linguotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFCckzqiFnSo7LjSdOc0Kx9BHQ23A73s4',
    appId: '1:691889381035:ios:c324e03d5a709732c221ee',
    messagingSenderId: '691889381035',
    projectId: 'linguotech-c7558',
    storageBucket: 'linguotech-c7558.appspot.com',
    iosBundleId: 'com.example.linguotech.RunnerTests',
  );
}
